### ISSUE TITLE
HTTPS to HTTP

### ISSUE THREAD

**Issue by wardrich** [chirag64/Imgur-To-Filmot#3]
Not sure if it's a proxy setting at my work, or just that FILMOT doesn't have https enabled, but I can never get https://imgur.com links to load when they are converted to https://filmot.org

**Comment by chirag64** [comment]
Just tried filmot.org from my home network, looks like filmot.org does not support https. Thanks for bringing this to my notice, I'll try to fix this up over the weekend.

**Comment by wardrich** [comment]
Any chance to look into this?  I've never worked with JS but I can do some googling to see if I can hack up a solution.

**Comment by chirag64** [comment]
This has been fixed in v1.50, it would take a few days for v1.50 to get listed on [Mozilla addons page](https://addons.mozilla.org/en-US/firefox/addon/imgur-to-filmot/) since it is pending review from the Mozilla team. Please let me know if after the update you're still facing this issue.

Thanks for reporting btw 👍🏼
